### ISSUE TITLE
Can't compile on debian testing

### ISSUE THREAD

**Issue by michl** [catch22/gitit-tasks#1]
Hey,

I love gitit and i guess i would love your plugin. I am running a debian testing machine, gitit just compiled fine using cabal. I checked out the latest version of gitit-tasks on github today. If I try to compile it witch `cabal install --user` it exits with this error message:

```
Resolving dependencies...
Configuring gitit-tasks-0.1...
Preprocessing library gitit-tasks-0.1...
Building gitit-tasks-0.1...
[1 of 1] Compiling Network.Gitit.Plugin.Tasks ( src/Network/Gitit/Plugin/Tasks.hs, dist/build/Network/Gitit/Plugin/Tasks.o )

src/Network/Gitit/Plugin/Tasks.hs:92:34:
    Not in scope: data constructor `EnDash'

src/Network/Gitit/Plugin/Tasks.hs:92:51:
    Not in scope: data constructor `EnDash'
cabal: Error: some packages failed to install:
gitit-tasks-0.1 failed during the building phase. The exception was:
ExitFailure 1
```

As I don't know haskell I have no idea, what ghc could be trying to tell me. I would appreciate if you could help me  with this.

Kind regards
Michael

**Comment by michl** [comment]
If I understand right, EnDash is a pandoc data type. I guess the exact version would help then: 

```
gitit@wiki:~$ pandoc -v
pandoc 1.9.1.2
Compiled with citeproc-hs 0.3.4, texmath 0.6.0.3, highlighting-kate
[...]
gitit@wiki:~$ gitit -v
gitit version 0.9 +plugins
```

**Comment by catch22** [comment]
Thank you for your bug report!

As you say, the problem is that pandoc changed its interface in the 1.9 series. Myself I'm still using pandoc 1.8.*. You can force both gitit-tasks to use an older version by changing the corresponding line in gitit-tasks.cabal to

```
pandoc >= 1.8.2 && < 1.9
pandoc-types >= 1.8.2 && < 1.9
```

However, this will most probably conflict with gitit's use of pandoc 1.9, though. Given pandoc's 

```
* Removed `Apostrophe`, `EmDash`, `EnDash`, and `Ellipses`
  from the native `Inline` type in pandoc-types.  Now we use `Str`
  elements with unicode.
```

you might rather want to fix gitit-tasks by replacing `EnDash` by `Str "–"` etc.! I'd be glad to take a patch. Please let me know how things turn out :)

**Comment by michl** [comment]
Thanks for the fast help. When I discovered that pandoc changed its interface I tried to switch back to pandoc-1.8 which broke the current version of gitit as you expected. Your suggested change in Tasks.hs however worked just fine. :-) I commited the change to my forked repo.
Again, thanks a lot, your plugin is great!
